db:
  username: postgres
  password: 123
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 1
    last: 2
    key: value
  pool:
    size: 10
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20

logging:
  level:
    root: WARN
    by.service: INFO
    by.servlets: INFO
  file:
    name: logFile
    path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/internet_shop_test
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false



